#!/bin/sh -e

SED=${SED:-sed}
DOCKER=${DOCKER:-docker}
SSH_KEYGEN=${SSH_KEYGEN:-ssh-keygen}

log() {
    echo '#' $@
}

cmd() {
    echo '$' $@
    $@
}

help_message() {
    local bold=$(tput bold) normal=$(tput sgr0)
    cat <<EOF
${bold}NAME${normal}
        bootstrap - install requirements for this tutorial

${bold}SYNOPSYS${normal}
        ${bold}bootstrap${normal} [OPTIONS]

${bold}DESCRIPTION${normal}
        This script installs the files in ${bold}base-image/files${normal} directory
        required by the ${bold}base-image/Dockerfile${normal} recipe:

        1. Generate a SSH key without passphrase, so that the different containers can 
           interact together.
        2. Download IBM Platform MPI Community Edition installer
        3. Build the base Docker image used by this tutorial

        ${bold}-h --help${normal}
                Display this message and exit.

${bold}ENVIRONMENT${normal}
        You can specify path to executables used by this script
        via environment variables if not in PATH:

        ${bold}SED${normal}
        ${bold}DOCKER${normal}
        ${bold}SSH_KEYGEN${normal}
EOF
}

parse_cli() {
    while [ "x$1" != x ] ; do
        case "$1" in
            -h|--help)
                help_message
                exit 0
                ;;
        esac
        shift
    done
}

generate_ssh_key() {
    if ! [ -f base-image/files/id_rsa ] ; then
        echo "$SSH_KEYGEN" -t rsa -N "''" -f base-image/files/id_rsa
        "$SSH_KEYGEN" -t rsa -N '' -f base-image/files/id_rsa
    fi
    cmd chmod 400 base-image/files/id_rsa
    cmd chmod 400 base-image/files/id_rsa.pub
}

download_platform_mpi() {
    PLATFORM_MPI_BIN=platform_mpi-09.01.04.03r-ce.bin
    PLATFORM_MPI_DOWNLOAD="https://www14.software.ibm.com/sdfdl/v2/regic/stgepm/fromibm/conf/ibmpmce/Xa.2/Xb.aWO8rUFWgTdbUXN5gKFlxFqJBvABCBKoZVZNLCorKlA/Xc.platform_mpi-09.01.04.03r-ce.bin/Xd./Xf.LPr.F1az/Xg.9204939/Xi.swg-ibmpmce/XY.regsrvs/XZ.d0PstIAclMb06sh1Daldud_jHwI/$PLATFORM_MPI_BIN"
    if ! [ -f "base-image/files/$PLATFORM_MPI_BIN" ] ;then
        log "Downloading IBM Platform MPI Community Edition"
        (cd base-image/files ; cmd wget "$PLATFORM_MPI_DOWNLOAD")
    else 
        log "IBM Platform MPI Community Edition already downloaded. Nothing to do."
    fi
    chmod +x "base-image/files/$PLATFORM_MPI_BIN"
}

build_docker_image() {
    log "Building base Docker image"
    cmd "$DOCKER" build -t centos7:mpi base-image
}

SSH_KEY=~/.ssh/id_rsa

parse_cli $@
download_platform_mpi
generate_ssh_key
build_docker_image
